forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'
urlpatterns = [
    # ex: /forum/
    path("", views.MainView.as_view(), name="index"),
    # ex: /forum/5/
    path("<int:pergunta_id>/", views.PerguntaView.as_view(), name="detalhe"),
    # ex: /forum/5/voto/
    path("<int:resposta_id>/voto/", views.VotoView.as_view(), name="voto"),
    # ex: /forum/inserir/
    path("inserir/", views.InserirPerguntaView.as_view(), name="inserir_pergunta"),
    # ex: /forum/5/resposta/
    path("<int:pergunta_id>/resposta/",
         views.InserirRespostaView.as_view(), name="inserir_resposta"),

]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path("forum/", include("forum.urls")),
]

forum/models.py
from django.db import models
import datetime 
from django.utils import timezone

class Pergunta(models.Model):
    titulo = models.CharField(max_length=200, null=False)
    detalhe = models.TextField(null=False)
    tentativa = models.TextField()
    data_criacao = models.DateTimeField(max_length=200, null=False, default="anônimo")

    def __str__(self):
        return "[" + str(self.id) + "] " + self.titulo
    def foi_publicado_recentemente(self):
        return self.data_criacao >= timezone.now() - datetime.timedelta(days=1)
    def string_detalhada(self):
        return "id: " + str (self.id) + "; titulo: " + self.titulo + "; detalhe: " + self.detalhe + "; tentativa: " + self.tentativa + "; data criação: " + str(self.data_criacao) + "; usuario: " + self.usuario

class Resposta(models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    texto = models.TextField(null=False)
    votos = models.IntegerField(default=0)
    data_criacao = models.DateTimeField("Criado em ")
    usuario = models.CharField(max_length=200, null=False, default="anônimo")

    def __str__(self):
        return "[" + str(self.id) + "] " + self.texto
    def foi_publicado_recentemente(self):
        return self.data_criacao >= timezone.now() - datetime.timedelta(days=1)
# Create your models here.

forum/views.py
from django.shortcuts import render

from django.http import HttpResponse, Http404
from .models import Pergunta, Resposta

from django.views import View

from django.utils import timezone
from django.shortcuts import redirect
from django.urls import reverse

class MainView(View):
    def get(self, request):
        lista_ultimas_questoes = Pergunta.objects.order_by("-data_criacao")
        contexto = {'perguntas' : lista_ultimas_questoes}
        return render(request, 'forum/index.html', contexto)

class PerguntaView(View):
    def get(self, request, pergunta_id):
        try:
            pergunta = Pergunta.objects.get(pk=pergunta_id)
        except Pergunta.DoesNotExist:
            raise Http404("Pergunta inexistente")
        contexto = {'pergunta' : pergunta}
        return render(request, 'forum/detalhe.html', contexto)

class VotoView(View):
    def get(self, request, resposta_id):
        try:
            resposta = Resposta.objects.get(pk=resposta_id)
        except Resposta.DoesNotExist:
            raise Http404("Resposta inexistente")
        return HttpResponse(str(resposta) + "; votos: " + str(resposta.votos))

    def post(self, request, resposta_id):
        try:
            resposta = Resposta.objects.get(pk=resposta_id)
        except Resposta.DoesNotExist:
            raise Http404("Resposta inexistente")
        resposta.votos += 1
        resposta.save()
        return redirect(reverse('forum:detalhe', args=[resposta.pergunta.id]))

class InserirPerguntaView(View):
    def get(self, request):
        return render(request, 'forum/inserir_pergunta.html')

    def post(self, request):
        if request.user.is_authenticated:
            usuario = request.user.username
        else:
            usuario = 'anônimo'
        titulo = request.POST.get('titulo')
        detalhe = request.POST.get('detalhe')
        tentativa = request.POST.get('tentativa')
        data_criacao = timezone.now()

        pergunta = Pergunta(titulo=titulo, detalhe=detalhe,
                            tentativa=tentativa, data_criacao=data_criacao, usuario=usuario)
        pergunta.save()

        return redirect(reverse('forum:detalhe', args=[pergunta.id]))

class InserirRespostaView(View):
    def get(self, request, pergunta_id):
        try:
            pergunta = Pergunta.objects.get(pk=pergunta_id)
        except Pergunta.DoesNotExist:
            raise Http404("Pergunta inexistente")
        contexto = {'pergunta' : pergunta}
        return render(request, 'forum/inserir_resposta.html', contexto)

    def post(self, request, pergunta_id):
        try:
            pergunta = Pergunta.objects.get(pk=pergunta_id)
        except Pergunta.DoesNotExist:
            raise Http404("Pergunta inexistente")

        if request.user.is_authenticated:
            usuario = request.user.username
        else:
            usuario = 'anônimo'
        texto = request.POST.get('texto')
        data_criacao = timezone.now()
        
        pergunta.resposta_set.create(texto=texto, data_criacao=data_criacao, usuario=usuario)

        return redirect(reverse('forum:detalhe', args=[pergunta.id]))

forum/templates/forum/base.html
<html>
<head>
    <title>Exemplo StackOverflow</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
</head>
<body>
    <header>
        <h1>Fórum MyStackOverflow</h1>
        <nav>
            <a href="{% url 'forum:index' %}">Home</a> | 
            <a href="{% url 'forum:inserir_pergunta' %}">Criar pergunta</a>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

forum/templates/forum/detalhe.html
{% extends "forum/base.html" %}

{% block content %}
<h2>{{ pergunta.titulo }}</h2>
<p><b>Descrição:</b> {{ pergunta.detalhe }}</p>
<p><b>Tentativas:</b> {{ pergunta.tentativa }}</p>
<p><b>Data:</b> {{ pergunta.data_criacao|date:"d/m/Y H:i" }}</p>
<p><b>Autor:</b> {{ pergunta.usuario }}</p>
{% block respostas %}
<h3>Respostas</h3>
<ul>
{% for resposta in pergunta.resposta_set.all %}
    <li>
        {{ resposta.texto }} - <b>{{ resposta.votos }} votos</b>
        <form action="{% url 'forum:voto' resposta.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Votar">
        </form>
    </li>

{% endfor %}
</ul>
<a href="{% url 'forum:inserir_resposta' pergunta.id %}">
    <button>Nova resposta</button>
</a>
{% endblock %}
{% endblock %}

forum/templates/forum/index.html
{% extends "forum/base.html" %}

{% block content %}
{% if perguntas %}
    <h2>Últimas perguntas</h2>
    <ul>
    {% for pergunta in perguntas %}
        <li>
            <a href="{% url 'forum:detalhe' pergunta.id %}">
                {{ pergunta.titulo }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Nenhuma pergunta disponível.</p>
{% endif %}
<a href="{% url 'forum:inserir_pergunta' %}">
    <button>Nova pergunta</button>
</a>
{% endblock %}

forum/templates/forum/inserir_pergunta.html
{% extends "forum/base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p><label for="titulo">Escreva sua pergunta:</label><br>
        <input type="text" name="titulo" id="titulo" size="50" maxlength="200">
    </p>
    <p><label for="detalhe">Detalhe o problema:<br />
            <textarea rows="6" cols="50" id="detalhe" name="detalhe"></textarea>
    </p>
    <p><label for="tentativa">Escreva o que você já tentou:<br />
            <textarea rows="6" cols="50" id="tentativa" name="tentativa"></textarea>
    </p>

    <input type="submit" name="dopost" value="Salvar" />

</form>
{% endblock %}

forum/templates/forum/inserir_resposta.html
{% extends "forum/detalhe.html" %}

{% block respostas %}
<h3>Adicionar resposta</h3>
<form method="post">
    {% csrf_token %}
    
        <textarea rows="6" cols="50" id="texto" name="texto"></textarea>
    <p>
    <input type="submit" value="Salvar">
</form>
{% endblock %}